"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:color_host)\
$os\
$hostname\
[\ue0ba](bg:color_host fg:color_user)\
$username\
[](bg:color_directory fg:color_user)\
$directory\
[](fg:color_directory bg:color_git)\
$git_branch\
$git_status\
[](fg:color_git bg:color_lang)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_lang bg:color_env)\
$docker_context\
$conda\
[](fg:color_env bg:color_time)\
$time\
[ ](fg:color_time)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_time = '#3c3836'
color_user = '#6495ED'
color_host = '#483D8B'

color_env = '#665c54'
color_lang = '#458588'
color_git = '#689d6a'
color_directory = '#008080'

color_green = '#4CAF50'
color_purple = '#9C27B0'
color_red = '#F44336'
color_yellow = '#FFEB3B'

[os]
disabled = false
style = "bg:color_host fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_user fg:color_fg0"
style_root = "bg:color_host fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:color_host fg:color_fg0"
format ='[ $ssh_symbol$hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_directory"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_git"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_git)]($style)'

[git_status]
style = "bg:color_git"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_git)]($style)'

[nodejs]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[c]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[rust]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[golang]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[php]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[java]
symbol = " "
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[kotlin]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[haskell]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[python]
symbol = ""
style = "bg:color_lang"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_lang)]($style)'

[docker_context]
symbol = ""
style = "bg:color_env"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_env)]($style)'

[conda]
style = "bg:color_env"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_env)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_time"
format = '[[  $time ](fg:color_fg0 bg:color_time)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
